export const GET_VIDEOS_REQUEST = "APP/GET_VIDEOS_REQUEST";
export const GET_VIDEOS_SUCCESS = "APP/GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAILURE = "APP/GET_VIDEOS_FAILURE";

export const SEARCH_REQUEST = "APP/SEARCH_REQUEST";
export const SEARCH_SUCCESS = "APP/SEARCH_SUCCESS";
export const SEARCH_FAILURE = "APP/SEARCH_FAILURE";